<?php
$value = static fn(string $key, string $default = ''): string => e((string) (($edit[$key] ?? $default)));
?>
<div class="admin-heading"><div><span>Digital Multi Sinergy</span><h1><?= e(ucfirst($tab)) ?></h1></div><?php if(in_array($tab,['products','articles','jobs'],true)): ?><a class="primary-action" href="<?= e(url('admin?tab='.$tab)) ?>">+ Konten baru</a><?php endif; ?></div>
<?php if($flash): ?><div class="notice <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>

<?php if($tab === 'overview'): ?>
<div class="metric-grid"><article><span>Products</span><strong><?= $counts['products'] ?></strong><a href="<?= e(url('admin?tab=products')) ?>">Kelola →</a></article><article><span>News</span><strong><?= $counts['articles'] ?></strong><a href="<?= e(url('admin?tab=articles')) ?>">Kelola →</a></article><article><span>Careers</span><strong><?= $counts['jobs'] ?></strong><a href="<?= e(url('admin?tab=jobs')) ?>">Kelola →</a></article><article><span>Open inquiries</span><strong><?= $counts['inquiries'] ?></strong><a href="<?= e(url('admin?tab=inquiries')) ?>">Lihat →</a></article></div>
<div class="admin-panel welcome"><div><span class="panel-label">CMS ONLINE</span><h2>Selamat datang di DMS CMS.</h2><p>Semua perubahan yang dipublish di sini langsung tampil di website publik. Gunakan status Draft untuk menyimpan konten yang belum siap.</p></div><a href="<?= e(url()) ?>" target="_blank">Preview website ↗</a></div>

<?php elseif($tab === 'settings'): ?>
<form class="admin-panel cms-form" method="post" action="<?= e(url('admin/settings')) ?>"><?= csrf_field() ?><div class="panel-title"><div><span class="panel-label">COMPANY PROFILE</span><h2>Informasi perusahaan</h2></div><button class="primary-action" type="submit">Simpan perubahan</button></div><div class="field-grid"><?php foreach(['company_name'=>'Nama perusahaan','company_tagline'=>'Tagline','email'=>'Email','phone'=>'Telepon','whatsapp'=>'WhatsApp','business_hours'=>'Jam kerja','instagram_url'=>'Instagram URL','linkedin_url'=>'LinkedIn URL','project_count'=>'Jumlah proyek','partner_count'=>'Jumlah partner','experience_years'=>'Tahun pengalaman'] as $key=>$label): ?><label><?= e($label) ?><input name="<?= e($key) ?>" value="<?= e($settings[$key]??'') ?>"></label><?php endforeach; ?><label class="wide">Alamat<textarea name="address"><?= e($settings['address']??'') ?></textarea></label><label class="wide">Google Maps query<input name="map_query" value="<?= e($settings['map_query']??'') ?>"><small>Gunakan nama lokasi/alamat tanpa URL.</small></label></div></form>

<?php elseif($tab === 'products'): ?>
<form class="admin-panel cms-form" method="post" enctype="multipart/form-data" action="<?= e(url('admin/content/save')) ?>"><?= csrf_field() ?><input type="hidden" name="type" value="products"><?php if($edit): ?><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><?php endif; ?><div class="panel-title"><div><span class="panel-label"><?= $edit?'EDIT':'NEW' ?> PRODUCT</span><h2><?= $edit?'Edit produk':'Tambah produk' ?></h2></div><button class="primary-action" type="submit">Simpan produk</button></div><div class="field-grid"><label>Nama (ID)<input name="title" required value="<?= $value('title') ?>"></label><label>Name (EN)<input name="title_en" required value="<?= $value('title_en') ?>"></label><label>Slug<input name="slug" value="<?= $value('slug') ?>" placeholder="otomatis dari nama"></label><label>Kategori<select name="category"><?php foreach(['Passive','Active','FTTx Tools','Software','IT & AI'] as $category): ?><option <?= ($edit['category']??'')===$category?'selected':'' ?>><?= e($category) ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="published" <?= ($edit['status']??'published')==='published'?'selected':'' ?>>Published</option><option value="draft" <?= ($edit['status']??'')==='draft'?'selected':'' ?>>Draft</option></select></label><label>Urutan<input type="number" name="sort_order" value="<?= $value('sort_order','0') ?>"></label><label class="wide">Ringkasan (ID)<textarea name="summary" required><?= $value('summary') ?></textarea></label><label class="wide">Summary (EN)<textarea name="summary_en" required><?= $value('summary_en') ?></textarea></label><label class="wide">Konten (ID)<textarea name="content"><?= $value('content') ?></textarea></label><label class="wide">Content (EN)<textarea name="content_en"><?= $value('content_en') ?></textarea></label><label>Nama file/URL gambar<input name="image" value="<?= $value('image') ?>"></label><label>Upload gambar<input type="file" name="image_upload" accept="image/jpeg,image/png,image/webp"></label><label class="wide">Spesifikasi JSON<textarea name="specs_json" placeholder='{"Fiber":"G657A2","Connector":"SC / LC"}'><?= $value('specs_json','{}') ?></textarea></label><label class="wide">Detail lengkap JSON <small>Gallery, features, applications, dan related products dari data prototype.</small><textarea name="details_json"><?= $value('details_json','{}') ?></textarea></label></div></form><?= cms_table('products',$products) ?>

<?php elseif($tab === 'articles'): ?>
<form class="admin-panel cms-form" method="post" enctype="multipart/form-data" action="<?= e(url('admin/content/save')) ?>"><?= csrf_field() ?><input type="hidden" name="type" value="articles"><?php if($edit): ?><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><?php endif; ?><div class="panel-title"><div><span class="panel-label"><?= $edit?'EDIT':'NEW' ?> ARTICLE</span><h2><?= $edit?'Edit artikel':'Tambah artikel' ?></h2></div><button class="primary-action" type="submit">Simpan artikel</button></div><div class="field-grid"><label>Judul (ID)<input name="title" required value="<?= $value('title') ?>"></label><label>Title (EN)<input name="title_en" required value="<?= $value('title_en') ?>"></label><label>Slug<input name="slug" value="<?= $value('slug') ?>"></label><label>Kategori (ID)<input name="category" required value="<?= $value('category','Teknologi') ?>"></label><label>Category (EN)<input name="category_en" required value="<?= $value('category_en','Technology') ?>"></label><label>Status<select name="status"><option value="published" <?= ($edit['status']??'published')==='published'?'selected':'' ?>>Published</option><option value="draft" <?= ($edit['status']??'')==='draft'?'selected':'' ?>>Draft</option></select></label><label>Tanggal publish<input type="datetime-local" name="published_at" value="<?= e(isset($edit['published_at'])?date('Y-m-d\TH:i',strtotime($edit['published_at'])):date('Y-m-d\TH:i')) ?>"></label><label class="wide">Excerpt (ID)<textarea name="excerpt" required><?= $value('excerpt') ?></textarea></label><label class="wide">Excerpt (EN)<textarea name="excerpt_en" required><?= $value('excerpt_en') ?></textarea></label><label class="wide">Konten (ID)<textarea name="content"><?= $value('content') ?></textarea></label><label class="wide">Content (EN)<textarea name="content_en"><?= $value('content_en') ?></textarea></label><label>Nama file/URL gambar<input name="image" value="<?= $value('image') ?>"></label><label>Upload gambar<input type="file" name="image_upload" accept="image/jpeg,image/png,image/webp"></label><label class="wide">Related article slugs (JSON)<textarea name="related_json"><?= $value('related_json','[]') ?></textarea></label></div></form><?= cms_table('articles',$articles) ?>

<?php elseif($tab === 'jobs'): ?>
<form class="admin-panel cms-form" method="post" action="<?= e(url('admin/content/save')) ?>"><?= csrf_field() ?><input type="hidden" name="type" value="jobs"><?php if($edit): ?><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><?php endif; ?><div class="panel-title"><div><span class="panel-label"><?= $edit?'EDIT':'NEW' ?> CAREER</span><h2><?= $edit?'Edit lowongan':'Tambah lowongan' ?></h2></div><button class="primary-action" type="submit">Simpan lowongan</button></div><div class="field-grid"><label>Posisi (ID)<input name="title" required value="<?= $value('title') ?>"></label><label>Position (EN)<input name="title_en" required value="<?= $value('title_en') ?>"></label><label>Slug<input name="slug" value="<?= $value('slug') ?>"></label><label>Departemen (ID)<input name="department" required value="<?= $value('department') ?>"></label><label>Department (EN)<input name="department_en" required value="<?= $value('department_en') ?>"></label><label>Lokasi<input name="location" required value="<?= $value('location','Jakarta') ?>"></label><label>Tipe pekerjaan (ID)<input name="employment_type" required value="<?= $value('employment_type','Penuh Waktu') ?>"></label><label>Employment type (EN)<input name="employment_type_en" required value="<?= $value('employment_type_en','Full-time') ?>"></label><label>Status<select name="status"><option value="published" <?= ($edit['status']??'published')==='published'?'selected':'' ?>>Published</option><option value="draft" <?= ($edit['status']??'')==='draft'?'selected':'' ?>>Draft</option></select></label><span></span><label class="wide">Deskripsi (ID)<textarea name="description" required><?= $value('description') ?></textarea></label><label class="wide">Description (EN)<textarea name="description_en" required><?= $value('description_en') ?></textarea></label></div></form><?= cms_table('jobs',$jobs) ?>

<?php elseif($tab === 'inquiries'): ?>
<div class="admin-panel"><div class="panel-title"><div><span class="panel-label">CONTACT FORM</span><h2>Incoming inquiries</h2></div></div><div class="inquiry-list"><?php foreach($inquiries as $inquiry): ?><article><header><div><span class="status <?= e($inquiry['status']) ?>"><?= e(str_replace('_',' ',$inquiry['status'])) ?></span><h3><?= e($inquiry['name']) ?> · <?= e($inquiry['company']) ?></h3><small><?= e(date('d M Y H:i',strtotime($inquiry['created_at']))) ?> · <?= e($inquiry['inquiry_type']) ?></small></div><form method="post" action="<?= e(url('admin/inquiry/status')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$inquiry['id'] ?>"><select name="status" onchange="this.form.submit()"><option value="new" <?= $inquiry['status']==='new'?'selected':'' ?>>New</option><option value="in_progress" <?= $inquiry['status']==='in_progress'?'selected':'' ?>>In progress</option><option value="closed" <?= $inquiry['status']==='closed'?'selected':'' ?>>Closed</option></select></form></header><p><?= nl2br(e($inquiry['message'])) ?></p><footer><a href="mailto:<?= e($inquiry['email']) ?>"><?= e($inquiry['email']) ?></a><a href="tel:<?= e(preg_replace('/[^0-9+]/','',$inquiry['phone'])) ?>"><?= e($inquiry['phone']) ?></a></footer></article><?php endforeach; ?><?php if(!$inquiries): ?><p>Belum ada inquiry.</p><?php endif; ?></div></div>
<?php else: ?><div class="admin-panel"><h2>Halaman tidak ditemukan.</h2></div><?php endif; ?>

<?php
function cms_table(string $type, array $rows): string
{
    ob_start(); ?>
    <div class="admin-panel content-list"><div class="panel-title"><div><span class="panel-label">PUBLISHED & DRAFT</span><h2>Daftar konten</h2></div></div><div class="table-wrap"><table><thead><tr><th>Title</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td data-label="Konten"><b><?= e($row['title']) ?></b><small><?= e($row['slug']) ?></small></td><td data-label="Status"><span class="status <?= e($row['status']) ?>"><?= e($row['status']) ?></span></td><td data-label="Diperbarui"><?= e(date('d M Y',strtotime($row['updated_at']))) ?></td><td data-label="Aksi"><div class="row-actions"><a href="<?= e(url('admin?tab='.$type.'&edit='.$row['id'])) ?>">Edit</a><form method="post" action="<?= e(url('admin/content/delete')) ?>" onsubmit="return confirm('Hapus konten ini?')"><?= csrf_field() ?><input type="hidden" name="type" value="<?= e($type) ?>"><input type="hidden" name="id" value="<?= (int)$row['id'] ?>"><button>Hapus</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
    <?php return (string) ob_get_clean();
}
?>
