<?php
$languageKey = current_language() === 'en' ? 'EN' : 'ID';
$detailSpecs = $details['specs'] ?? [];
$features = $details['features'] ?? [];
$applications = $details['applications'] ?? [];
$gallery = array_slice($details['gallery'] ?? [], 0, 3);
if (!$detailSpecs) {
    foreach ((json_decode($product['specs_json'] ?: '{}', true) ?: []) as $label => $specValue) $detailSpecs[] = ['label' => ['ID' => $label, 'EN' => $label], 'value' => $specValue];
}
?>
<section class="section detail-page product-detail"><div class="container breadcrumbs"><a href="<?= e(url('products')) ?>"><?= e(tr('Produk','Products')) ?></a><span>/</span><span><?= e($product['category']) ?></span><span>/</span><span><?= e(localized($product,'title')) ?></span></div><div class="container detail-grid"><div class="detail-visual reveal"><div class="detail-image parallax-image"><img src="<?= e(image_url($product['image'])) ?>" alt="<?= e(localized($product,'title')) ?>"></div><?php if($gallery): ?><div class="product-gallery"><?php foreach($gallery as $galleryImage): ?><a href="<?= e($galleryImage) ?>" target="_blank" rel="noopener"><img src="<?= e($galleryImage) ?>" alt="<?= e(localized($product,'title')) ?>" loading="lazy"></a><?php endforeach; ?></div><?php endif; ?></div><div class="detail-copy reveal"><span class="eyebrow"><?= e($product['category']) ?></span><h1><?= e(localized($product,'title')) ?></h1><?php if(!empty($details['tagline'][$languageKey])): ?><p class="product-tagline"><?= e($details['tagline'][$languageKey]) ?></p><?php endif; ?><p class="lead"><?= e(localized($product,'content')) ?></p><a class="btn" href="<?= e(url('contact?product='.urlencode($product['title']))) ?>"><?= e(tr('Minta Penawaran','Request a Quote')) ?> →</a><?php if($detailSpecs): ?><div class="specs"><h2><?= e(tr('Spesifikasi Utama','Key Specifications')) ?></h2><?php foreach($detailSpecs as $spec): ?><div><span><?= e($spec['label'][$languageKey] ?? $spec['label']['EN'] ?? '') ?></span><b><?= e((string) ($spec['value'] ?? '')) ?></b></div><?php endforeach; ?></div><?php endif; ?></div></div></section>

<?php if($features || $applications): ?><section class="section soft product-benefits"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Detail Produk','Product Details')) ?></span><h2><?= e(tr('Dirancang untuk implementasi yang andal.','Designed for dependable implementation.')) ?></h2></div><div class="container benefit-columns"><?php if($features): ?><article class="reveal"><span>01</span><h3><?= e(tr('Fitur Utama','Key Features')) ?></h3><ul><?php foreach($features as $feature): ?><li><?= e($feature[$languageKey] ?? '') ?></li><?php endforeach; ?></ul></article><?php endif; ?><?php if($applications): ?><article class="reveal"><span>02</span><h3><?= e(tr('Aplikasi','Applications')) ?></h3><ul><?php foreach($applications as $application): ?><li><?= e($application[$languageKey] ?? '') ?></li><?php endforeach; ?></ul></article><?php endif; ?></div></section><?php endif; ?>

<?php if($relatedProducts): ?><section class="section related-section"><div class="container section-head inline reveal"><div><span class="eyebrow"><?= e(tr('Produk Terkait','Related Products')) ?></span><h2><?= e(tr('Lengkapi kebutuhan proyek Anda.','Complete your project requirements.')) ?></h2></div><a class="text-link" href="<?= e(url('products')) ?>"><?= e(tr('Lihat semua produk','View all products')) ?> →</a></div><div class="container product-grid stagger"><?php foreach($relatedProducts as $related): ?><article class="product-card"><a class="product-image" href="<?= e(url('products/'.$related['slug'])) ?>"><img src="<?= e(image_url($related['image'])) ?>" alt="<?= e(localized($related,'title')) ?>" loading="lazy"></a><div><small><?= e($related['category']) ?></small><h2><a href="<?= e(url('products/'.$related['slug'])) ?>"><?= e(localized($related,'title')) ?></a></h2><p><?= e(localized($related,'summary')) ?></p></div></article><?php endforeach; ?></div></section><?php endif; ?>
