<section class="page-hero about-hero"><div class="container page-hero-copy reveal"><span class="eyebrow"><?= e(tr('Tentang DMS','About DMS')) ?></span><h1><?= e(tr('Menghubungkan bisnis dengan teknologi yang bekerja nyata.','Connecting businesses with technology that works in the real world.')) ?></h1><p><?= e(tr('Sejak 2021, kami menghadirkan solusi ICT dan digital yang relevan, andal, dan siap berkembang bersama pelanggan.','Since 2021, we have delivered relevant, dependable ICT and digital solutions built to grow with our customers.')) ?></p></div></section>

<section class="section about-overview"><div class="container two-col about-intro"><div class="reveal"><span class="eyebrow"><?= e(tr('Profil Perusahaan','Company Profile')) ?></span><h2><?= e(tr('Satu partner untuk konektivitas, infrastruktur, dan solusi digital.','One partner for connectivity, infrastructure, and digital solutions.')) ?></h2></div><div class="reveal"><p><?= e(tr('Digital Multi Sinergy adalah system integrator teknologi yang membantu operator telekomunikasi, perusahaan, dan institusi membangun solusi dari tahap perencanaan hingga implementasi.','Digital Multi Sinergy is a technology systems integrator helping telecommunications operators, enterprises, and institutions build solutions from planning through implementation.')) ?></p><p><?= e(tr('Pendekatan kami menggabungkan pengetahuan produk, rekayasa teknis, dan eksekusi lapangan agar investasi teknologi memberikan dampak nyata.','Our approach combines product knowledge, technical engineering, and field execution so technology investments deliver tangible impact.')) ?></p></div></div></section>

<section class="section soft"><div class="container stats-grid stagger"><article><strong><?= e($settings['experience_years']) ?></strong><span><?= e(tr('Tahun bertumbuh','Years growing')) ?></span></article><article><strong><?= e($settings['project_count']) ?></strong><span><?= e(tr('Proyek & implementasi','Projects & implementations')) ?></span></article><article><strong><?= e($settings['partner_count']) ?></strong><span><?= e(tr('Partner ekosistem','Ecosystem partners')) ?></span></article></div></section>

<section class="section dark values-section"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Nilai Kami','Our Values')) ?></span><h2><?= e(tr('Fondasi untuk setiap solusi yang kami hadirkan.','The foundation behind every solution we deliver.')) ?></h2></div><div class="container value-grid stagger"><article><span>01</span><h3><?= e(tr('Integritas','Integrity')) ?></h3><p><?= e(tr('Komunikasi terbuka, rekomendasi jujur, dan komitmen yang dapat diandalkan.','Open communication, honest recommendations, and commitments you can rely on.')) ?></p></article><article><span>02</span><h3><?= e(tr('Kolaborasi','Collaboration')) ?></h3><p><?= e(tr('Bekerja sebagai satu tim bersama pelanggan, partner, dan engineer lapangan.','Working as one team with customers, partners, and field engineers.')) ?></p></article><article><span>03</span><h3><?= e(tr('Inovasi Praktis','Practical Innovation')) ?></h3><p><?= e(tr('Teknologi dipilih untuk menyelesaikan kebutuhan nyata, bukan sekadar mengikuti tren.','Technology selected to solve real needs, not simply follow trends.')) ?></p></article></div></section>

<section class="section"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Cara Kami Bekerja','How We Work')) ?></span><h2><?= e(tr('Jelas dari kebutuhan hingga operasional.','Clarity from requirements to operations.')) ?></h2></div><div class="container process-grid stagger"><article><b>01</b><h3><?= e(tr('Memahami','Understand')) ?></h3><p><?= e(tr('Memetakan tujuan bisnis, kebutuhan teknis, dan kondisi lapangan.','Map business goals, technical needs, and field conditions.')) ?></p></article><article><b>02</b><h3><?= e(tr('Merancang','Design')) ?></h3><p><?= e(tr('Menentukan arsitektur, produk, dan tahapan implementasi.','Define the architecture, products, and implementation stages.')) ?></p></article><article><b>03</b><h3><?= e(tr('Menghadirkan','Deliver')) ?></h3><p><?= e(tr('Mengeksekusi, menguji, mendokumentasikan, dan mendukung solusi.','Execute, test, document, and support the solution.')) ?></p></article></div></section>

<section class="section soft industries"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Industri yang Dilayani','Industries We Serve')) ?></span><h2><?= e(tr('Pengalaman lintas kebutuhan dan skala.','Experience across needs and scale.')) ?></h2></div><div class="container industry-list stagger"><?php foreach ([tr('Telekomunikasi','Telecommunications'),tr('Enterprise','Enterprise'),tr('Pemerintahan','Government'),tr('Pendidikan','Education'),tr('Data Center','Data Center'),tr('Property & Hospitality','Property & Hospitality')] as $industry): ?><span><?= e($industry) ?></span><?php endforeach; ?></div></section>
