<section class="home-hero">
    <div class="hero-media" data-parallax=".12"><img src="<?= e(asset('images/hero-fiber.webp')) ?>" alt="" fetchpriority="high"><i></i></div>
    <div class="hero-orbits" aria-hidden="true"><i></i><i></i><b></b></div>
    <div class="container hero-copy"><span class="eyebrow eyebrow-center">Digital Multi Sinergy</span><h1><?= current_language() === 'en' ? 'Technology &amp; Connectivity <em>Solutions</em> Built for Tomorrow.' : 'Solusi Teknologi &amp;<br>Konektivitas untuk <em>Masa Depan.</em>' ?></h1><p><?= e(tr('Menyediakan konektivitas, telekomunikasi, IT, dan solusi teknologi yang andal melalui produk berkualitas dan implementasi profesional.','Delivering reliable connectivity, telecommunications, IT and technology solutions through quality products and professional implementation.')) ?></p><div class="button-row"><a class="btn" href="<?= e(url('contact')) ?>"><?= e(tr('Konsultasi Gratis Tersedia','Free Consultation Available')) ?> <span>→</span></a><a class="btn btn-outline" href="<?= e(url('products')) ?>"><?= e(tr('Jelajahi Produk','Explore Products')) ?></a></div></div>
    <a class="scroll-cue" href="#solutions">↓</a>
</section>
<div class="wave dark-white"><svg viewBox="0 0 1440 70" preserveAspectRatio="none"><path d="M0 25c360 62 720-18 1080 25 170 20 285-10 360-25v45H0Z"/></svg></div>

<section class="section products-home" id="solutions"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Produk Kami','Our Products')) ?></span><h2><?= e(tr('Solusi untuk infrastruktur konektivitas modern.','Solutions for modern connectivity infrastructure.')) ?></h2></div><div class="container card-grid stagger">
<?php foreach ($products as $index => $product): ?><a class="solution-card" href="<?= e(url('products/' . $product['slug'])) ?>"><div class="card-image"><img src="<?= e(image_url($product['image'])) ?>" alt="<?= e(localized($product,'title')) ?>" loading="lazy"><span><?= str_pad((string)($index+1),2,'0',STR_PAD_LEFT) ?></span></div><div class="card-body"><small><?= e($product['category']) ?></small><h3><?= e(localized($product,'title')) ?></h3><p><?= e(localized($product,'summary')) ?></p><b><?= e(tr('Pelajari lebih lanjut','Learn more')) ?> →</b></div></a><?php endforeach; ?>
</div></section>

<div class="wave white-dark"><svg viewBox="0 0 1440 60" preserveAspectRatio="none"><path d="M0 26c430 40 960-20 1440 5v29H0Z"/></svg></div><section class="dark-cta"><div class="container reveal"><h2><?= e(tr('Mari bangun solusi teknologi yang tepat bersama.','Let’s build the right technology solution together.')) ?></h2><p><?= e(tr('Bicarakan proyek konektivitas, infrastruktur, atau digital Anda bersama tim kami.','Talk with our team about your connectivity, infrastructure, or digital project.')) ?></p><a class="btn btn-orange" href="<?= e(url('contact')) ?>"><?= e(tr('Mulai Konsultasi','Start a Consultation')) ?> →</a></div></section><div class="wave dark-white"><svg viewBox="0 0 1440 60" preserveAspectRatio="none"><path d="M0 28c430-28 930 32 1440 0v32H0Z"/></svg></div>

<section class="section capabilities"><div class="container two-col"><div class="reveal"><span class="eyebrow"><?= e(tr('Kemampuan','Capabilities')) ?></span><h2><?= e(tr('Dari infrastruktur ke solusi digital cerdas.','From infrastructure to intelligent digital solutions.')) ?></h2><div class="capability-list"><?php foreach ([tr('Infrastruktur Fiber Optik','Fiber Optic Infrastructure'),tr('Jaringan & Konektivitas','Network & Connectivity'),tr('Produk Telekomunikasi','Telecommunications Products'),tr('Deployment FTTx','FTTx Deployment'),tr('Pengembangan Software','Software Development'),tr('Solusi IT & AI','IT & AI Solutions')] as $capability): ?><span><i></i><?= e($capability) ?></span><?php endforeach; ?></div><a class="text-link" href="<?= e(url('about')) ?>"><?= e(tr('Lebih lanjut tentang DMS','More about DMS')) ?> →</a></div><div class="capability-photo reveal"><img src="<?= e(asset('images/service-active.webp')) ?>" alt="DMS capability" loading="lazy"><div><strong><?= e($settings['project_count']) ?></strong><span><?= e(tr('Proyek diimplementasikan','Projects implemented')) ?></span></div></div></div></section>

<section class="section soft projects"><div class="container section-head reveal"><span class="eyebrow"><?= e(tr('Teknologi dalam Aksi','Technology in Action')) ?></span><h2><?= e(tr('Implementasi yang dirancang untuk hasil nyata.','Implementation designed for real outcomes.')) ?></h2></div><div class="container project-list stagger">
<?php $cases=[['implementation-fiber.webp','Telekomunikasi',tr('Implementasi Backbone Fiber Optik','Fiber Optic Backbone Implementation'),tr('Deployment end-to-end termasuk splicing, testing, dan dokumentasi.','End-to-end deployment including splicing, testing, and documentation.')],['implementation-enterprise.webp','Enterprise',tr('Modernisasi Jaringan Enterprise','Enterprise Network Modernization'),tr('Structured cabling, perangkat aktif, dan platform monitoring terintegrasi.','Structured cabling, active equipment, and an integrated monitoring platform.')],['implementation-digital.webp',tr('Pemerintah','Government'),tr('Transformasi Platform Digital','Digital Platform Transformation'),tr('Platform digital dengan analitik AI dan otomasi proses operasional.','A digital platform with AI analytics and operational automation.')]]; foreach($cases as $i=>$case): ?><article class="project-card <?= $i%2 ? 'reverse':'' ?>"><div class="project-image"><img src="<?= e(asset('images/'.$case[0])) ?>" alt="<?= e($case[2]) ?>" loading="lazy"><span><?= e($case[1]) ?></span></div><div class="project-copy"><b>0<?= $i+1 ?></b><small><?= e(tr('Studi Implementasi','Implementation Study')) ?></small><h3><?= e($case[2]) ?></h3><p><?= e($case[3]) ?></p></div></article><?php endforeach; ?>
</div></section>

<section class="section dark why"><div class="container section-head center reveal"><span class="eyebrow eyebrow-center"><?= e(tr('Mengapa DMS','Why DMS')) ?></span><h2><?= e(tr('Partner teknologi yang fokus pada implementasi.','A technology partner focused on implementation.')) ?></h2></div><div class="container value-grid stagger"><article><span>◈</span><h3><?= e(tr('Solusi Andal','Reliable Solutions')) ?></h3><p><?= e(tr('Produk dan arsitektur yang dipilih berdasarkan kebutuhan operasional nyata.','Products and architectures selected around real operational needs.')) ?></p></article><article><span>◉</span><h3><?= e(tr('Keahlian Teknis','Technical Expertise')) ?></h3><p><?= e(tr('Tim berpengalaman di fiber optic, network, software, dan solusi IT.','An experienced team across fiber optics, networks, software, and IT solutions.')) ?></p></article><article><span>◆</span><h3><?= e(tr('Dukungan End-to-End','End-to-End Support')) ?></h3><p><?= e(tr('Dari konsultasi, instalasi, commissioning, hingga dukungan berkelanjutan.','From consultation and installation to commissioning and ongoing support.')) ?></p></article></div></section>

<section class="section soft news-home"><div class="container section-head inline reveal"><div><span class="eyebrow"><?= e(tr('Wawasan & Pembaruan','Insights & Updates')) ?></span><h2><?= e(tr('Berita Terbaru','Latest News')) ?></h2></div><a class="text-link" href="<?= e(url('news')) ?>"><?= e(tr('Semua Artikel','All Articles')) ?> →</a></div><div class="container news-grid stagger"><?php foreach($articles as $article): ?><article class="news-card"><a class="news-image" href="<?= e(url('news/'.$article['slug'])) ?>"><img src="<?= e(image_url($article['image'])) ?>" alt="<?= e(localized($article,'title')) ?>" loading="lazy"></a><div><span><?= e($article['category']) ?></span><time><?= e(date('d M Y',strtotime($article['published_at']))) ?></time><h3><a href="<?= e(url('news/'.$article['slug'])) ?>"><?= e(localized($article,'title')) ?></a></h3><p><?= e(localized($article,'excerpt')) ?></p><a class="text-link" href="<?= e(url('news/'.$article['slug'])) ?>"><?= e(tr('Baca Artikel','Read Article')) ?> →</a></div></article><?php endforeach; ?></div></section>
